python3: can't open file '/home/ubuntu/PlayDate_Revision/PlayDate/application/PlayDate/playdate/manage.py': [Errno 2] No such file or directory
